begin;
grant vida_identity_owner to postgres with inherit true, set true;

do $preflight$
declare v_missing text[]:=array[]::text[];v_name text;
begin
 foreach v_name in array array['economic_entities','client_accounts','client_account_vri_links','client_account_entities','client_account_users','client_account_user_authorizations','planning_engagements','planning_engagement_vri_links','planning_engagement_entities','planning_engagement_transitions','client_activation_seeds'] loop if to_regclass(format('public.%I',v_name)) is null then v_missing:=array_append(v_missing,v_name);end if;end loop;
 if cardinality(v_missing)>0 then raise exception 'M3 ABORTADA: tabelas esperadas ausentes: %',array_to_string(v_missing,', ');end if;
 if to_regprocedure('vida_internal.is_account_member(uuid)') is null or to_regprocedure('vida_internal.has_role_in_scope(uuid,text[],uuid,uuid)') is null or to_regprocedure('vida_internal.is_staff(uuid)') is null or to_regprocedure('vida_internal.has_entity_specific_role(uuid,text[],uuid)') is null or to_regprocedure('vida_internal.has_engagement_specific_role(uuid,text[],uuid)') is null or to_regprocedure('public.create_economic_entity(uuid,text,text)') is null or to_regprocedure('public.create_planning_engagement(uuid,uuid,text,text,text)') is null or to_regprocedure('public.grant_client_account_authorization(uuid,uuid,text,text,uuid,uuid)') is null or to_regprocedure('public.revoke_client_account_authorization(uuid)') is null or to_regprocedure('public.record_planning_engagement_transition(uuid,text,text,text,text,text,text)') is null or to_regprocedure('public.add_client_account_membership(uuid,uuid,text)') is null or to_regprocedure('public.remove_client_account_membership(uuid,uuid,text)') is null or to_regprocedure('public.activate_client_from_vri(uuid,text,text,text,uuid,text,text)') is null then raise exception 'M3 ABORTADA: uma ou mais funções M2 esperadas não existem';end if;
end;$preflight$;

alter table public.economic_entities enable row level security;alter table public.client_accounts enable row level security;alter table public.client_account_vri_links enable row level security;alter table public.client_account_entities enable row level security;alter table public.client_account_users enable row level security;alter table public.client_account_user_authorizations enable row level security;alter table public.planning_engagements enable row level security;alter table public.planning_engagement_vri_links enable row level security;alter table public.planning_engagement_entities enable row level security;alter table public.planning_engagement_transitions enable row level security;alter table public.client_activation_seeds enable row level security;
revoke all on table public.economic_entities,public.client_accounts,public.client_account_vri_links,public.client_account_entities,public.client_account_users,public.client_account_user_authorizations,public.planning_engagements,public.planning_engagement_vri_links,public.planning_engagement_entities,public.planning_engagement_transitions,public.client_activation_seeds from public,anon,authenticated,service_role;
grant select on table public.economic_entities,public.client_accounts,public.client_account_vri_links,public.client_account_entities,public.client_account_users,public.client_account_user_authorizations,public.planning_engagements,public.planning_engagement_vri_links,public.planning_engagement_entities,public.planning_engagement_transitions to authenticated;
grant update on table public.economic_entities to authenticated;grant insert,delete on table public.client_account_entities to authenticated;grant insert,delete on table public.planning_engagement_entities to authenticated;
grant select on table public.economic_entities,public.client_accounts,public.client_account_vri_links,public.client_account_entities,public.client_account_users,public.client_account_user_authorizations,public.planning_engagements,public.planning_engagement_vri_links,public.planning_engagement_entities,public.planning_engagement_transitions to service_role;
grant usage on schema vida_internal to authenticated;grant execute on function vida_internal.is_account_member(uuid) to authenticated;grant execute on function vida_internal.has_role_in_scope(uuid,text[],uuid,uuid) to authenticated;grant execute on function vida_internal.is_staff(uuid) to authenticated;grant execute on function vida_internal.has_entity_specific_role(uuid,text[],uuid) to authenticated;grant execute on function vida_internal.has_engagement_specific_role(uuid,text[],uuid) to authenticated;
grant execute on function public.create_economic_entity(uuid,text,text) to authenticated;grant execute on function public.create_planning_engagement(uuid,uuid,text,text,text) to authenticated;grant execute on function public.grant_client_account_authorization(uuid,uuid,text,text,uuid,uuid) to authenticated;grant execute on function public.revoke_client_account_authorization(uuid) to authenticated;grant execute on function public.record_planning_engagement_transition(uuid,text,text,text,text,text,text) to authenticated;grant execute on function public.add_client_account_membership(uuid,uuid,text) to authenticated;grant execute on function public.remove_client_account_membership(uuid,uuid,text) to authenticated;
grant execute on function public.activate_client_from_vri(uuid,text,text,text,uuid,text,text) to service_role;revoke execute on function vida_internal.bootstrap_client_account(uuid,text) from service_role;

create policy economic_entities_select on public.economic_entities for select to authenticated using(exists(select 1 from public.client_account_entities cae where cae.economic_entity_id=economic_entities.id and (vida_internal.is_staff(cae.client_account_id) or vida_internal.has_entity_specific_role(cae.client_account_id,array['client_primary','client_participant','external_advisor'],economic_entities.id))));
create policy economic_entities_update on public.economic_entities for update to authenticated using(exists(select 1 from public.client_account_entities cae where cae.economic_entity_id=economic_entities.id and vida_internal.is_staff(cae.client_account_id))) with check(exists(select 1 from public.client_account_entities cae where cae.economic_entity_id=economic_entities.id and vida_internal.is_staff(cae.client_account_id)));
create policy economic_entities_insert on public.economic_entities for insert to authenticated with check(false);
create policy client_accounts_select on public.client_accounts for select to authenticated using(vida_internal.is_account_member(id));
create policy client_account_vri_links_select on public.client_account_vri_links for select to authenticated using(vida_internal.is_staff(client_account_id));
create policy client_account_entities_select on public.client_account_entities for select to authenticated using(vida_internal.is_staff(client_account_id) or vida_internal.has_entity_specific_role(client_account_id,array['client_primary','client_participant','external_advisor'],economic_entity_id));
create policy client_account_entities_insert on public.client_account_entities for insert to authenticated with check(vida_internal.is_staff(client_account_id));
create policy client_account_entities_delete on public.client_account_entities for delete to authenticated using(vida_internal.is_staff(client_account_id));
create policy client_account_users_select on public.client_account_users for select to authenticated using(auth_user_id=auth.uid() or vida_internal.is_staff(client_account_id));
create policy client_account_user_authorizations_select on public.client_account_user_authorizations for select to authenticated using(auth_user_id=auth.uid() or vida_internal.is_staff(client_account_id));
create policy planning_engagements_select on public.planning_engagements for select to authenticated using(vida_internal.is_staff(client_account_id) or vida_internal.has_engagement_specific_role(client_account_id,array['client_primary','client_participant','external_advisor'],id));
create policy planning_engagement_vri_links_select on public.planning_engagement_vri_links for select to authenticated using(vida_internal.is_staff(client_account_id));
create policy planning_engagement_entities_select on public.planning_engagement_entities for select to authenticated using(vida_internal.is_staff(client_account_id) or (vida_internal.has_engagement_specific_role(client_account_id,array['client_primary','client_participant','external_advisor'],planning_engagement_id) and vida_internal.has_entity_specific_role(client_account_id,array['client_primary','client_participant','external_advisor'],economic_entity_id)));
create policy planning_engagement_entities_insert on public.planning_engagement_entities for insert to authenticated with check(vida_internal.is_staff(client_account_id));
create policy planning_engagement_entities_delete on public.planning_engagement_entities for delete to authenticated using(vida_internal.is_staff(client_account_id));
create policy planning_engagement_transitions_select on public.planning_engagement_transitions for select to authenticated using(exists(select 1 from public.planning_engagements pe where pe.id=planning_engagement_transitions.planning_engagement_id and vida_internal.is_staff(pe.client_account_id)));

grant vida_identity_owner to postgres with inherit false, set true;
commit;