-- VIDA OS™ — Gate 002 v4 / M2.02
-- Planning Engagement core with production ownership semantics.

begin;
grant vida_identity_owner to postgres with inherit true, set true;
grant create on schema public to vida_identity_owner;
grant usage,create on schema vida_internal to vida_identity_owner;

create table public.planning_engagements (
 id uuid primary key default gen_random_uuid(), client_account_id uuid not null references public.client_accounts(id),
 state text not null default 'onboarding_em_andamento' check(state in ('onboarding_em_andamento','dados_incompletos','dados_completos','diagnostico_em_elaboracao','diagnostico_validado','plano_em_elaboracao','plano_aprovado','implementacao','acompanhamento','revisao','documentos_pendentes','pausado','encerrado_concluido','encerrado_cancelado','abandonado')),
 state_before_pause text check(state_before_pause is null or state_before_pause in ('onboarding_em_andamento','dados_incompletos','dados_completos','diagnostico_em_elaboracao','diagnostico_validado','plano_em_elaboracao','plano_aprovado','implementacao','acompanhamento','revisao','documentos_pendentes')),
 predecessor_engagement_id uuid references public.planning_engagements(id), opened_at timestamptz not null default now(), closed_at timestamptz, created_at timestamptz not null default now(),
 constraint chk_closed_at_matches_state check((state in ('encerrado_concluido','encerrado_cancelado','abandonado') and closed_at is not null) or (state not in ('encerrado_concluido','encerrado_cancelado','abandonado') and closed_at is null)),
 constraint chk_state_before_pause_matches check((state='pausado' and state_before_pause is not null) or (state<>'pausado' and state_before_pause is null)),
 constraint chk_predecessor_not_self check(predecessor_engagement_id is null or predecessor_engagement_id<>id),
 constraint uq_planning_engagements_account_id unique(client_account_id,id)
);
alter table public.client_account_user_authorizations add constraint client_account_user_authorizations_engagement_fkey foreign key(client_account_id,planning_engagement_id) references public.planning_engagements(client_account_id,id);
create table public.planning_engagement_vri_links(client_account_id uuid not null,planning_engagement_id uuid primary key references public.planning_engagements(id),vri_activation_correlation_id text not null check(btrim(vri_activation_correlation_id)<>''),created_at timestamptz not null default now(),foreign key(client_account_id,planning_engagement_id) references public.planning_engagements(client_account_id,id));
create unique index planning_engagement_vri_links_correlation_id_uq on public.planning_engagement_vri_links(vri_activation_correlation_id);
create function vida_internal.guard_planning_engagement_state_change() returns trigger language plpgsql set search_path='' as $$ begin if new.id is distinct from old.id or new.client_account_id is distinct from old.client_account_id or new.predecessor_engagement_id is distinct from old.predecessor_engagement_id or new.opened_at is distinct from old.opened_at or new.created_at is distinct from old.created_at then raise exception 'campos estruturais do engagement são imutáveis após a criação'; end if; if (new.state is distinct from old.state or new.closed_at is distinct from old.closed_at or new.state_before_pause is distinct from old.state_before_pause) and coalesce(current_setting('vida_os.allow_engagement_state_change',true),'')<>'on' then raise exception 'state, closed_at e state_before_pause só mudam via record_planning_engagement_transition()'; end if; return new; end; $$;
revoke all on function vida_internal.guard_planning_engagement_state_change() from public, anon, authenticated, service_role;
create trigger planning_engagements_guard_state_change before update on public.planning_engagements for each row execute function vida_internal.guard_planning_engagement_state_change();
create function vida_internal.validate_planning_engagement_predecessor() returns trigger language plpgsql set search_path='' as $$ declare v_predecessor_account_id uuid; v_predecessor_state text; begin if new.predecessor_engagement_id is not null then select client_account_id,state into v_predecessor_account_id,v_predecessor_state from public.planning_engagements where id=new.predecessor_engagement_id; if v_predecessor_account_id is null then raise exception 'predecessor_engagement_id % não encontrado',new.predecessor_engagement_id; end if; if v_predecessor_account_id<>new.client_account_id then raise exception 'predecessor_engagement_id deve pertencer à mesma client_account'; end if; if v_predecessor_state not in ('encerrado_concluido','encerrado_cancelado','abandonado') then raise exception 'predecessor_engagement_id % não está em estado terminal (estado atual: %)',new.predecessor_engagement_id,v_predecessor_state; end if; end if; return new; end; $$;
revoke all on function vida_internal.validate_planning_engagement_predecessor() from public, anon, authenticated, service_role;
create trigger planning_engagements_validate_predecessor before insert or update on public.planning_engagements for each row execute function vida_internal.validate_planning_engagement_predecessor();
create table public.planning_engagement_entities(client_account_id uuid not null,planning_engagement_id uuid not null,economic_entity_id uuid not null,created_at timestamptz not null default now(),primary key(planning_engagement_id,economic_entity_id),foreign key(client_account_id,planning_engagement_id) references public.planning_engagements(client_account_id,id) on delete restrict,foreign key(client_account_id,economic_entity_id) references public.client_account_entities(client_account_id,economic_entity_id) on delete restrict);
create index planning_engagement_entities_economic_entity_id_idx on public.planning_engagement_entities(economic_entity_id);
create table public.planning_engagement_transitions(id uuid primary key default gen_random_uuid(),planning_engagement_id uuid not null references public.planning_engagements(id),from_state text check(from_state is null or from_state in ('onboarding_em_andamento','dados_incompletos','dados_completos','diagnostico_em_elaboracao','diagnostico_validado','plano_em_elaboracao','plano_aprovado','implementacao','acompanhamento','revisao','documentos_pendentes','pausado','encerrado_concluido','encerrado_cancelado','abandonado')),to_state text not null check(to_state in ('onboarding_em_andamento','dados_incompletos','dados_completos','diagnostico_em_elaboracao','diagnostico_validado','plano_em_elaboracao','plano_aprovado','implementacao','acompanhamento','revisao','documentos_pendentes','pausado','encerrado_concluido','encerrado_cancelado','abandonado')),event text not null,required_document text,actor_auth_user_id uuid references auth.users(id) on delete set null,actor_label text not null,executor_role text not null check(executor_role in ('planner_owner','internal_staff','system')),reason text,origin text not null check(origin in ('system','planner','client','external')),automatic_effect text,occurred_at timestamptz not null default now(),constraint chk_reason_required_for_terminal_states check(to_state not in ('encerrado_concluido','encerrado_cancelado','abandonado') or (reason is not null and btrim(reason)<>'')));
create index planning_engagement_transitions_engagement_id_idx on public.planning_engagement_transitions(planning_engagement_id,occurred_at);
create function vida_internal.guard_planning_engagement_transition_immutable() returns trigger language plpgsql set search_path='' as $$ begin if new.actor_auth_user_id is distinct from old.actor_auth_user_id and not(old.actor_auth_user_id is not null and new.actor_auth_user_id is null) then raise exception 'actor_auth_user_id só pode transicionar de um valor para NULL'; end if; if new.id is distinct from old.id or new.planning_engagement_id is distinct from old.planning_engagement_id or new.from_state is distinct from old.from_state or new.to_state is distinct from old.to_state or new.event is distinct from old.event or new.required_document is distinct from old.required_document or new.actor_label is distinct from old.actor_label or new.executor_role is distinct from old.executor_role or new.reason is distinct from old.reason or new.origin is distinct from old.origin or new.automatic_effect is distinct from old.automatic_effect or new.occurred_at is distinct from old.occurred_at then raise exception 'planning_engagement_transitions é imutável — apenas actor_auth_user_id pode ser nulificado por integridade referencial'; end if; return new; end; $$;
revoke all on function vida_internal.guard_planning_engagement_transition_immutable() from public, anon, authenticated, service_role;
create trigger planning_engagement_transitions_guard_immutable before update on public.planning_engagement_transitions for each row execute function vida_internal.guard_planning_engagement_transition_immutable();
create trigger planning_engagement_transitions_forbid_delete before delete on public.planning_engagement_transitions for each row execute function vida_internal.forbid_update_delete();
create index planning_engagements_client_account_id_idx on public.planning_engagements(client_account_id);
create function vida_internal.is_valid_planning_engagement_transition(p_from_state text,p_to_state text) returns boolean language sql immutable set search_path='' as $$ select (p_from_state is null and p_to_state='onboarding_em_andamento') or (p_from_state,p_to_state) in (('onboarding_em_andamento','dados_incompletos'),('onboarding_em_andamento','dados_completos'),('onboarding_em_andamento','documentos_pendentes'),('documentos_pendentes','dados_incompletos'),('documentos_pendentes','dados_completos'),('dados_incompletos','dados_completos'),('dados_incompletos','documentos_pendentes'),('dados_completos','diagnostico_em_elaboracao'),('diagnostico_em_elaboracao','diagnostico_validado'),('diagnostico_validado','plano_em_elaboracao'),('plano_em_elaboracao','plano_aprovado'),('plano_aprovado','implementacao'),('implementacao','acompanhamento'),('diagnostico_validado','encerrado_concluido'),('plano_aprovado','encerrado_concluido'),('implementacao','encerrado_concluido'),('acompanhamento','revisao'),('acompanhamento','dados_incompletos'),('acompanhamento','diagnostico_em_elaboracao'),('acompanhamento','plano_em_elaboracao'),('acompanhamento','encerrado_concluido'),('revisao','acompanhamento'),('revisao','dados_incompletos'),('revisao','diagnostico_em_elaboracao'),('revisao','plano_em_elaboracao'),('revisao','encerrado_concluido')) or (p_to_state='pausado' and p_from_state not in ('encerrado_concluido','encerrado_cancelado','abandonado','pausado')) or (p_to_state in ('encerrado_cancelado','abandonado') and p_from_state not in ('encerrado_concluido','encerrado_cancelado','abandonado','pausado')); $$;
revoke all on function vida_internal.is_valid_planning_engagement_transition(text,text) from public, anon, authenticated, service_role;

alter table public.planning_engagements owner to vida_identity_owner;
alter table public.planning_engagement_vri_links owner to vida_identity_owner;
alter table public.planning_engagement_entities owner to vida_identity_owner;
alter table public.planning_engagement_transitions owner to vida_identity_owner;
alter function vida_internal.guard_planning_engagement_state_change() owner to vida_identity_owner;
alter function vida_internal.validate_planning_engagement_predecessor() owner to vida_identity_owner;
alter function vida_internal.guard_planning_engagement_transition_immutable() owner to vida_identity_owner;
alter function vida_internal.is_valid_planning_engagement_transition(text,text) owner to vida_identity_owner;

revoke create on schema public from vida_identity_owner;
revoke create on schema vida_internal from vida_identity_owner;
grant vida_identity_owner to postgres with inherit false, set true;
commit;
