begin;
grant vida_identity_owner to postgres with inherit true, set true;
grant create on schema public to vida_identity_owner;
grant usage,create on schema vida_internal to vida_identity_owner;

do $preflight$
declare v_existing text[]:=array[]::text[];
begin
 if to_regclass('public.client_account_users') is null or to_regclass('public.client_account_user_authorizations') is null or to_regclass('public.client_accounts') is null then raise exception 'M2.1 ABORTADA: M2 core ausente'; end if;
 if to_regnamespace('vida_internal') is null then raise exception 'M2.1 ABORTADA: schema vida_internal ausente'; end if;
 if to_regclass('public.client_account_membership_events') is not null then v_existing:=array_append(v_existing,'client_account_membership_events'); end if;
 if to_regprocedure('public.add_client_account_membership(uuid,uuid,text)') is not null then v_existing:=array_append(v_existing,'add_client_account_membership'); end if;
 if to_regprocedure('public.remove_client_account_membership(uuid,uuid,text)') is not null then v_existing:=array_append(v_existing,'remove_client_account_membership'); end if;
 if to_regprocedure('vida_internal.insert_membership_backend(uuid,uuid)') is not null then v_existing:=array_append(v_existing,'insert_membership_backend'); end if;
 if cardinality(v_existing)>0 then raise exception 'M2.1 ABORTADA: objetos C1 já existem: %',array_to_string(v_existing,', '); end if;
end;$preflight$;

create table public.client_account_membership_events(id uuid primary key default gen_random_uuid(),event_type text not null check(event_type in ('added','removed')),client_account_id uuid not null references public.client_accounts(id) on delete restrict,auth_user_id uuid not null,actor_auth_user_id uuid,actor_type text not null check(actor_type in ('authenticated','backend_system')),justification text not null check(btrim(justification)<>''),occurred_at timestamptz not null default clock_timestamp(),constraint membership_event_actor_matches_type check((actor_type='authenticated' and actor_auth_user_id is not null) or (actor_type='backend_system' and actor_auth_user_id is null)));
alter table public.client_account_membership_events enable row level security;
revoke all on table public.client_account_membership_events from public,anon,authenticated,service_role;
create trigger client_account_membership_events_forbid_update before update on public.client_account_membership_events for each row execute function vida_internal.forbid_update_delete();
create trigger client_account_membership_events_forbid_delete before delete on public.client_account_membership_events for each row execute function vida_internal.forbid_update_delete();

create function vida_internal.guard_membership_canonical_mutation() returns trigger language plpgsql set search_path='' as $$ begin if coalesce(current_setting('vida_os.allow_membership_mutation',true),'')<>'on' then raise exception 'client_account_users só pode mudar via workflow canônico de membership/offboarding'; end if; return case when TG_OP='DELETE' then old else new end; end; $$;
revoke all on function vida_internal.guard_membership_canonical_mutation() from public,anon,authenticated,service_role;
create trigger client_account_users_canonical_insert_guard before insert on public.client_account_users for each row execute function vida_internal.guard_membership_canonical_mutation();
create trigger client_account_users_canonical_delete_guard before delete on public.client_account_users for each row execute function vida_internal.guard_membership_canonical_mutation();

create function public.add_client_account_membership(p_client_account_id uuid,p_auth_user_id uuid,p_justification text) returns boolean language plpgsql security definer set search_path='' as $$ declare v_actor uuid;v_previous_guard text;begin v_actor:=vida_internal.current_auth_uid();if v_actor is null then raise exception 'add_client_account_membership exige sessão autenticada';end if;if p_client_account_id is null or p_auth_user_id is null then raise exception 'client_account_id e auth_user_id são obrigatórios';end if;if p_justification is null or btrim(p_justification)='' then raise exception 'justification é obrigatória e não pode ser vazia';end if;perform 1 from public.client_accounts where id=p_client_account_id for update;if not found then raise exception 'client_account % inexistente',p_client_account_id;end if;if not vida_internal.has_role_in_scope(p_client_account_id,array['planner_owner']) then raise exception 'usuário % não é planner_owner desta conta — não pode adicionar membership',v_actor;end if;if not public.vida_auth_user_exists(p_auth_user_id) then raise exception 'auth_user_id % não existe',p_auth_user_id;end if;if exists(select 1 from public.client_account_users where client_account_id=p_client_account_id and auth_user_id=p_auth_user_id) then return false;end if;v_previous_guard:=current_setting('vida_os.allow_membership_mutation',true);perform set_config('vida_os.allow_membership_mutation','on',true);begin insert into public.client_account_users(client_account_id,auth_user_id) values(p_client_account_id,p_auth_user_id);exception when others then perform set_config('vida_os.allow_membership_mutation',coalesce(v_previous_guard,''),true);raise;end;perform set_config('vida_os.allow_membership_mutation',coalesce(v_previous_guard,''),true);insert into public.client_account_membership_events(event_type,client_account_id,auth_user_id,actor_auth_user_id,actor_type,justification) values('added',p_client_account_id,p_auth_user_id,v_actor,'authenticated',btrim(p_justification));return true;end;$$;
revoke all on function public.add_client_account_membership(uuid,uuid,text) from public,anon,authenticated,service_role;

create function public.remove_client_account_membership(p_client_account_id uuid,p_auth_user_id uuid,p_justification text) returns boolean language plpgsql security definer set search_path='' as $$ declare v_actor uuid;v_actor_label text;v_previous_guard text;begin v_actor:=vida_internal.current_auth_uid();if v_actor is null then raise exception 'remove_client_account_membership exige sessão autenticada';end if;if p_client_account_id is null or p_auth_user_id is null then raise exception 'client_account_id e auth_user_id são obrigatórios';end if;if p_justification is null or btrim(p_justification)='' then raise exception 'justification é obrigatória e não pode ser vazia';end if;perform 1 from public.client_accounts where id=p_client_account_id for update;if not found then raise exception 'client_account % inexistente',p_client_account_id;end if;if not vida_internal.has_role_in_scope(p_client_account_id,array['planner_owner']) then raise exception 'usuário % não é planner_owner desta conta — não pode remover membership',v_actor;end if;if not exists(select 1 from public.client_account_users where client_account_id=p_client_account_id and auth_user_id=p_auth_user_id) then return false;end if;if exists(select 1 from public.client_account_user_authorizations where client_account_id=p_client_account_id and auth_user_id=p_auth_user_id and role='planner_owner' and scope_type='account' and revoked_at is null) and not exists(select 1 from public.client_account_user_authorizations where client_account_id=p_client_account_id and auth_user_id is distinct from p_auth_user_id and role='planner_owner' and scope_type='account' and revoked_at is null) then raise exception 'não é possível remover o membership do último planner_owner account-scope da conta %',p_client_account_id;end if;v_actor_label:=vida_internal.auth_user_display_label(v_actor);update public.client_account_user_authorizations set revoked_at=clock_timestamp(),revoked_by=v_actor,revoked_by_label=v_actor_label where client_account_id=p_client_account_id and auth_user_id=p_auth_user_id and revoked_at is null;v_previous_guard:=current_setting('vida_os.allow_membership_mutation',true);perform set_config('vida_os.allow_membership_mutation','on',true);begin delete from public.client_account_users where client_account_id=p_client_account_id and auth_user_id=p_auth_user_id;exception when others then perform set_config('vida_os.allow_membership_mutation',coalesce(v_previous_guard,''),true);raise;end;perform set_config('vida_os.allow_membership_mutation',coalesce(v_previous_guard,''),true);insert into public.client_account_membership_events(event_type,client_account_id,auth_user_id,actor_auth_user_id,actor_type,justification) values('removed',p_client_account_id,p_auth_user_id,v_actor,'authenticated',btrim(p_justification));return true;end;$$;
revoke all on function public.remove_client_account_membership(uuid,uuid,text) from public,anon,authenticated,service_role;

create function vida_internal.insert_membership_backend(p_client_account_id uuid,p_auth_user_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ declare v_previous_guard text;begin if vida_internal.current_auth_uid() is not null then raise exception 'insert_membership_backend é backend-only';end if;if p_client_account_id is null or p_auth_user_id is null then raise exception 'client_account_id e auth_user_id são obrigatórios';end if;perform 1 from public.client_accounts where id=p_client_account_id for update;if not found then raise exception 'client_account % inexistente',p_client_account_id;end if;if not public.vida_auth_user_exists(p_auth_user_id) then raise exception 'auth_user_id % não existe',p_auth_user_id;end if;if exists(select 1 from public.client_account_users where client_account_id=p_client_account_id and auth_user_id=p_auth_user_id) then return false;end if;v_previous_guard:=current_setting('vida_os.allow_membership_mutation',true);perform set_config('vida_os.allow_membership_mutation','on',true);begin insert into public.client_account_users(client_account_id,auth_user_id) values(p_client_account_id,p_auth_user_id);exception when others then perform set_config('vida_os.allow_membership_mutation',coalesce(v_previous_guard,''),true);raise;end;perform set_config('vida_os.allow_membership_mutation',coalesce(v_previous_guard,''),true);insert into public.client_account_membership_events(event_type,client_account_id,auth_user_id,actor_auth_user_id,actor_type,justification) values('added',p_client_account_id,p_auth_user_id,null,'backend_system','provisionamento inicial canônico via VRI');return true;end;$$;
revoke all on function vida_internal.insert_membership_backend(uuid,uuid) from public,anon,authenticated,service_role;

create or replace function vida_internal.bootstrap_client_account(p_planner_auth_user_id uuid,p_vri_correlation_id text default null) returns uuid language plpgsql security definer set search_path='' as $$ declare v_account_id uuid;v_existing_account_id uuid;v_existing_bootstrap_id uuid;v_label text;begin if vida_internal.current_auth_uid() is not null then raise exception 'bootstrap_client_account é função de provisionamento backend — não deve ser chamada em sessão interativa (auth.uid() = %)',vida_internal.current_auth_uid();end if;if p_vri_correlation_id is not null and btrim(p_vri_correlation_id)='' then raise exception 'p_vri_correlation_id não pode ser string vazia — use NULL para "sem token"';end if;if p_vri_correlation_id is not null then select client_account_id,bootstrap_planner_auth_user_id into v_existing_account_id,v_existing_bootstrap_id from public.client_account_vri_links where vri_correlation_id=p_vri_correlation_id;if found then if v_existing_bootstrap_id<>p_planner_auth_user_id then raise exception 'vri_correlation_id % já foi processado com planner_auth_user_id incompatível',p_vri_correlation_id;end if;return v_existing_account_id;end if;end if;insert into public.client_accounts default values returning id into v_account_id;if p_vri_correlation_id is not null then begin insert into public.client_account_vri_links(client_account_id,vri_correlation_id,bootstrap_planner_auth_user_id) values(v_account_id,p_vri_correlation_id,p_planner_auth_user_id);exception when unique_violation then delete from public.client_accounts where id=v_account_id;select client_account_id,bootstrap_planner_auth_user_id into v_account_id,v_existing_bootstrap_id from public.client_account_vri_links where vri_correlation_id=p_vri_correlation_id;if v_existing_bootstrap_id<>p_planner_auth_user_id then raise exception 'vri_correlation_id % já foi processado com planner_auth_user_id incompatível (corrida concorrente)',p_vri_correlation_id;end if;return v_account_id;end;end if;perform vida_internal.insert_membership_backend(v_account_id,p_planner_auth_user_id);v_label:=vida_internal.auth_user_display_label(p_planner_auth_user_id);insert into public.client_account_user_authorizations(client_account_id,auth_user_id,auth_user_label,role,scope_type,granted_by,granted_by_label) values(v_account_id,p_planner_auth_user_id,v_label,'planner_owner','account',null,'sistema (bootstrap)');return v_account_id;end;$$;
revoke all on function vida_internal.bootstrap_client_account(uuid,text) from public,anon,authenticated,service_role;

alter table public.client_account_membership_events owner to vida_identity_owner;
alter function vida_internal.guard_membership_canonical_mutation() owner to vida_identity_owner;
alter function public.add_client_account_membership(uuid,uuid,text) owner to vida_identity_owner;
alter function public.remove_client_account_membership(uuid,uuid,text) owner to vida_identity_owner;
alter function vida_internal.insert_membership_backend(uuid,uuid) owner to vida_identity_owner;
alter function vida_internal.bootstrap_client_account(uuid,text) owner to vida_identity_owner;

revoke create on schema public from vida_identity_owner;
revoke create on schema vida_internal from vida_identity_owner;
grant vida_identity_owner to postgres with inherit false, set true;
commit;